name: Automated E2E Testing

on:
  push:
      branches:
        - master
        - workflow
        - cypress-test
  pull_request:
      branches:
        - master
        - workflow
  workflow_dispatch:

jobs:
    run-e2e-tests:
        name: Run E2E Tests
        runs-on: ubuntu-latest
        steps:
          - name: Checkout under $GITHUB_WORKSPACE
            uses: actions/checkout@v2
          
          - name: run cypress tests with electron
            uses: cypress-io/github-action@v2
            with:
              browser: electron
                