name: Automated Unit Testing
on:
  pull_request:
    branches:
        - workflow
  workflow_dispatch:

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/setup-node@v2
        

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install all dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test:jest